augmentation:
    Blur:
        blur_limit: 7
        always_apply: False
        p: 0.5
    GaussianBlur:
        blur_limit: [3, 7]
        sigma_limit: 0
        always_apply: False
        p: 0.5
    MedianBlur:
        blur_limit: 9
        always_apply: False
        p: 0.5
    MotionBlur:
        always_apply: False
        p: 0.5
    ErrorAug:
        always_apply: False
        p: 0.5
    CLAHE:
        clip_limit: [1, 4]
        tile_grid_size: [8, 8]
        always_apply: False
        p: 0.5
    ChannelDropout:
        channel_drop_range: [1, 3]
        fill_value: 0
        always_apply: False
        p: 0.5
    ChannelShuffle:
        always_apply: False
        p: 0.5
    ColorJitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.2
        always_apply: False
        p: 0.5
    Downscale:
        scale_min: 0.25
        scale_max: 0.25
        interpolation: 0
        always_apply: False
        p: 0.5
    Emboss:
        alpha: [0.2, 0.5]
        strength: [0.2, 0.7]
        always_apply: False
        p: 0.5
    Equalize:
        mode: 'cv'
        by_channels: True
        mask: None
        mask_params: []
        always_apply: False
        p: 0.5
    FancyPCA:
        alpha: 0.1
        always_apply: False
        p: 0.5
    GaussNoise:
        var_limit: [10.0, 50.0]
        mean: 0
        per_channel: True
        always_apply: False
        p: 0.5
    HueSaturationValue:
        hue_shift_limit: 20
        sat_shift_limit: 30
        val_shift_limit: 20
        always_apply: False
        p: 0.5
    ISONoise:
        color_shift: [0.01, 0.05]
        intensity: [0.1, 0.5]
        always_apply: False
        p: 0.5
    InvertImg:
        always_apply: False
        p: 0.5
    MultiplicativeNoise:
        multiplier: [0.9, 1.1]
        per_channel: False
        elementwise: False
        always_apply: False
        p: 0.5
    Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        max_pixel_value: 255
        always_apply: False
        p: 1.0
    RGBShift:
        r_shift_limit: 20
        g_shift_limit: 20
        b_shift_limit: 20
        always_apply: False
        p: 0.5
    RandomBrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.2
        brightness_by_max: True
        always_apply: False
        p: 0.5
    RandomFog:
        fog_coef_lower: 0.3
        fog_coef_upper: 1
        alpha_coef: 0.08
        always_apply: False
        p: 0.5
    RandomGamma:
        gamma_limit: [80, 120]
        eps: None
        always_apply: False
        p: 0.5
    RandomRain:
        slant_lower: -10
        slant_upper: 10
        drop_length: 20
        drop_width: 1
        drop_color: [200, 200, 200]
        blur_value: 7
        brightness_coefficient: 0.7
        rain_type: None
        always_apply: False
        p: 0.5
    RandomSnow:
        snow_point_lower: 0.1
        snow_point_upper: 0.3
        brightness_coeff: 2.5
        always_apply: False
        p: 0.5
    RandomShadow:
        shadow_roi: [0, 0.5, 1, 1]
        num_shadows_lower: 1
        num_shadows_upper: 2
        shadow_dimension: 5
        always_apply: False
        p: 0.5
    RandomSunFlare:
        flare_roi: [0, 0, 1, 0.5]
        angle_lower: 0
        angle_upper: 1
        num_flare_circles_lower: 6
        num_flare_circles_upper: 10
        src_radius: 400
        src_color: [255, 255, 255]
        always_apply: False
        p: 0.5
    RandomToneCurve:
        scale: 0.1
        always_apply: False
        p: 0.5
    Sharpen:
        alpha: [0.2, 0.5]
        lightness: [0.5, 1.0]
        always_apply: False
        p: 0.5
    Solarize:
        threshold: 128
        always_apply: False
        p: 0.5
    Superpixels:
        p_replace: 0.1
        n_segments: 100
        max_size: 128
        interpolation: 1
        always_apply: False
        p: 0.5
    ToSepia:
        always_apply: False
        p: 0.5