# mkdocs.yml
site_name: PyPlatypus Docs

theme:
  name: "material"

plugins:
- mkdocstrings

nav:
  - Welcome!: index.md
  - The Creators: authors.md
  - Platypus Input: platypus_input.md
  - Platypus Engine: platypus_engine.md
  - But why?: explanation.md
  - The Data Science Bowl Example: data_science_bowl_notebook/data_science_bowl_notebook.md
  