"""Every field in the configuration says what it is.

A `description` is not decoration: it is what `spec_schema()` publishes, what the YAML
reference on both documentation sites shows, and the only place a reader learns something
the code knows and the name does not - that `spatial_dropout` does nothing unless
`dropout` is above 0, that `he_*` initialisers pair with ReLU-like activations, that
`alpha` is a class weight in focal and the weight on false negatives in Tversky. Coverage
went from 49/197 to 197/197 writing them; without this test it only goes one way.

**Driven from the schema, and that is the point of this file.** The first version walked
the model tree by hand and reported 162 fields at 100% - while the schema said 87%,
because the walk never unwrapped `Annotated`, so every callback, metric and augmentation
model was invisible to it: 25 properties in 11 models. Worse, the guard written to stop
exactly that ("more than 150 fields, more than 20 models") passed, because 162 > 150 with
a third of the tree missing. The schema is generated by pydantic from the models, so
reading it needs no traversal of mine to get wrong - and it is also the artefact that is
published, which is what the claim is about.

Two things this catches that reading the source does not:

- **A field redeclared in a subclass loses the base's description.** pydantic does not
  inherit it, and the four overrides here (`task` and `subdirs`, on both tasks) were
  silently blank while the base looked documented.
- **Documentation written as a `#:` comment never arrives.** `SplitSpec` carried three
  carefully written blocks above `fractions`, `group_by` and `seed`; pydantic does not read
  them, so none of it reached the schema, an error message, or either site.
"""

import pytest

from pyplatypus import spec_schema

SCHEMA = spec_schema()
DEFS = SCHEMA["$defs"]
FIELDS = [
    (model, field, body)
    for model, definition in sorted(DEFS.items())
    for field, body in sorted(definition.get("properties", {}).items())
]


def test_the_schema_covers_the_whole_configuration():
    """Or this file passes by looking at part of it, which is how the previous version of
    this test reported 100% at 87%."""
    models = {model for model, _, _ in FIELDS}
    assert len(FIELDS) > 180
    assert len(models) > 35
    # the four corners: both tasks' data and models have to be in here
    for expected in ("SegmentationData", "DetectionData", "SegmentationModel", "DetectionModel"):
        assert expected in DEFS
    # and so do the ones the hand-rolled walk missed
    for expected in ("EarlyStopping", "IouMetric", "AugmentationStep", "Swa"):
        assert expected in DEFS


@pytest.mark.parametrize(
    ("model", "field"),
    [(model, field) for model, field, _ in FIELDS],
    ids=[f"{model}.{field}" for model, field, _ in FIELDS],
)
def test_every_field_has_a_description(model, field):
    body = next(b for m, f, b in FIELDS if (m, f) == (model, field))
    assert body.get("description"), (
        f"{model}.{field} has no description. It is a configuration field, so the "
        f"description is what the schema publishes and what the YAML reference shows."
    )


def test_descriptions_say_something():
    """A three-word description passes the check above and tells a reader nothing. The R
    package documented `eps` as "Per optimiser." for months, and `block_width` here was
    "Convolutions per block." until this test asked."""
    thin = [
        f"{model}.{field}"
        for model, field, body in FIELDS
        if body.get("description") and len(body["description"]) < 30
    ]
    assert thin == []
