#!/usr/bin/env python
"""Write `_quarto.yml` from `tools/reference-groups.yml`.

The grouping is a judgement and lives in that file; this turns it into the two things that
have to agree about it - quartodoc's `sections`, which decide what gets a page, and the
website sidebar, which decides what can be clicked. Generated rather than typed twice,
because 48 entries in two places is 48 chances to disagree.

The sidebar is the reason this exists at all. `auto: reference/*` lists every generated
page in one flat section - measured: 50 items, one section - while the R package's sidebar
has eight nested groups. A flat list of fifty is not navigation.

Run it after adding or renaming a public symbol. `tests/test_reference_groups.py` fails
when the two have drifted.
"""

from __future__ import annotations

import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
GROUPS = ROOT / "tools" / "reference-groups.yml"
CONFIG = ROOT / "_quarto.yml"

HEADER = """# GENERATED by tools/build_reference.py from tools/reference-groups.yml. Do not edit the
# `quartodoc.sections` or the sidebar's Reference section here; edit the grouping there.
#
# The engine's documentation, deliberately the same shape as the R package's site - same
# Quarto, same `_brand.yml`, the same eight groups - because a reader moving between them
# should not have to learn a second site. Verified rather than asserted: both sites produce
# a byte-identical bootstrap stylesheet, which Quarto names by the hash of its content.
#
# The reference is generated by quartodoc from the docstrings, so it cannot drift from the
# code, and the `>>>` examples in it are run by pytest - which means the site cannot show
# an example that does not work.
"""


# The About section is built from the files that are there. The R package's site had two
# sidebar entries that could not be clicked because the template named a `LICENCE` it spells
# `LICENSE` and a CHANGELOG it does not have; deriving it means an entry cannot outlive its
# file. The inverse applies here - this repository *does* have a CHANGELOG.md, and the
# first version of this generator had no About section at all.
# Markdown files Quarto can render into pages of the site.
ABOUT_PAGES = [
    ("Changelog", "CHANGELOG.md"),
    ("Code of conduct", "CODE_OF_CONDUCT.md"),
]

# `LICENSE` carries no extension, so Quarto will not make a page of it and renaming a
# licence file to suit a documentation generator is the wrong way round. It is linked where
# it lives instead, which is also where anyone checking a licence expects to look.
ABOUT_LINKS = [
    ("Licence", "https://github.com/maju116/pyplatypus/blob/main/LICENSE"),
]


def about_files() -> list[str]:
    return [name for _, name in ABOUT_PAGES if (ROOT / name).exists()]


def sidebar_about() -> list[dict]:
    entries = []
    for text, name in ABOUT_PAGES:
        if not (ROOT / name).exists():
            print(f"About: skipping {text} - no {name}")
            continue
        entries.append({"text": text, "file": name})
    entries.extend({"text": text, "href": href} for text, href in ABOUT_LINKS)
    return entries


def sidebar_reference(groups: list[dict]) -> list[dict]:
    return [
        {
            "section": group["title"],
            "contents": [f"reference/{entry}.qmd" for entry in group["contents"]],
        }
        for group in groups
    ]


def main() -> None:
    groups = yaml.safe_load(GROUPS.read_text())["groups"]

    config = {
        "project": {
            "type": "website",
            "output-dir": "docs",
            # An explicit list: a Quarto project at the repository root would otherwise
            # render README.md and CHANGELOG.md as pages of the site.
            # Named individually rather than by a glob: a glob would also pull in
            # README.md, which is GitHub's front page and opens with badges that mean
            # nothing on a site carrying its own navigation.
            "render": ["index.qmd", "reference/", *about_files()],
        },
        "brand": "_brand.yml",
        "website": {
            "title": "pyplatypus",
            "favicon": "assets/hexsticker.png",
            "navbar": {
                "search": True,
                "right": [
                    {
                        "icon": "github",
                        "href": "https://github.com/maju116/pyplatypus",
                        "aria-label": "pyplatypus on GitHub",
                    }
                ],
            },
            "sidebar": {
                "style": "docked",
                "collapse-level": 2,
                "contents": [
                    {"text": "Home", "file": "index.qmd"},
                    {
                        "section": "Reference",
                        "contents": [
                            # quartodoc's listing carries each group's description, which
                            # the sidebar does not show, so it is worth keeping - but it
                            # inherits the section's title and would read "Reference"
                            # twice.
                            {"text": "Overview", "file": "reference/index.qmd"},
                            *sidebar_reference(groups),
                        ],
                    },
                    {"section": "About", "contents": sidebar_about()},
                ],
            },
        },
        "format": {"html": {"toc": True}},
        "quartodoc": {
            "package": "pyplatypus",
            "dir": "reference",
            "title": "Reference",
            "style": "pkgdown",
            "render_interlinks": False,
            # Our docstrings are Google-style - `Args:`, `Returns:`, `Raises:` - and saying
            # so matters twice. It is what they are, and quartodoc otherwise reaches for the
            # NumPy parser, which in the installed griffe raises
            # `parse_numpy() got an unexpected keyword argument` and takes the build with it.
            "parser": "google",
            "sections": groups,
        },
    }

    CONFIG.write_text(HEADER + yaml.safe_dump(config, sort_keys=False, width=92))
    print(f"_quarto.yml: {len(groups)} groups, {sum(len(g['contents']) for g in groups)} entries")


if __name__ == "__main__":
    main()
