#!/usr/bin/env python
"""Write `_quarto.yml` from `tools/reference-groups.yml`.

The grouping is a judgement and lives in that file; this turns it into the two things that
have to agree about it - quartodoc's `sections`, which decide what gets a page, and the
website sidebar, which decides what can be clicked. Generated rather than typed twice,
because 48 entries in two places is 48 chances to disagree.

The sidebar is the reason this exists at all. `auto: reference/*` lists every generated
page in one flat section - measured: 50 items, one section - while the R package's sidebar
has eight nested groups. A flat list of fifty is not navigation.

Run it after adding or renaming a public symbol. `tests/test_reference_groups.py` fails
when the two have drifted.
"""

from __future__ import annotations

import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
GROUPS = ROOT / "tools" / "reference-groups.yml"
CONFIG = ROOT / "_quarto.yml"

HEADER = """# GENERATED by tools/build_reference.py from tools/reference-groups.yml. Do not edit the
# `quartodoc.sections` or the sidebar's Reference section here; edit the grouping there.
#
# The engine's documentation, deliberately the same shape as the R package's site - same
# Quarto, same `_brand.yml`, the same eight groups - because a reader moving between them
# should not have to learn a second site. Verified rather than asserted: both sites produce
# a byte-identical bootstrap stylesheet, which Quarto names by the hash of its content.
#
# The reference is generated by quartodoc from the docstrings, so it cannot drift from the
# code, and the `>>>` examples in it are run by pytest - which means the site cannot show
# an example that does not work.
"""


# The About section is built from the files that are there. The R package's site had two
# sidebar entries that could not be clicked because the template named a `LICENCE` it spells
# `LICENSE` and a CHANGELOG it does not have; deriving it means an entry cannot outlive its
# file. The inverse applies here - this repository *does* have a CHANGELOG.md, and the
# first version of this generator had no About section at all.
# One ordered list rather than pages-then-links, because the order is the point: it is the
# order the R package's sidebar uses, so a reader moving between the two sites finds the same
# things in the same places. Two lists forced Licence before Citation and could not express
# this one.
#
# `LICENSE` carries no extension, so Quarto will not make a page of it, and renaming a licence
# file to suit a documentation generator is the wrong way round. It is linked where it lives,
# which is also where anyone checking a licence expects to look.
ABOUT = [
    ("Changelog", "page", "CHANGELOG.md"),
    ("Code of conduct", "page", "CODE_OF_CONDUCT.md"),
    ("Licence", "link", "https://github.com/maju116/pyplatypus/blob/main/LICENSE"),
    ("Citation", "page", "CITATION.qmd"),
]

CITATION_CFF = ROOT / "CITATION.cff"
CITATION_PAGE = ROOT / "CITATION.qmd"


def build_citation_page() -> None:
    """The Citation page, rendered from `CITATION.cff` so the two cannot disagree.

    The R package needs no equivalent file: `citation("platypus")` is generated from its
    DESCRIPTION, which is R's own convention, and altdoc renders that into its site. CFF is
    this language's convention and GitHub reads it for "Cite this repository", so the facts
    live there once and this page is a view of them.
    """
    if not CITATION_CFF.exists():
        return
    meta = yaml.safe_load(CITATION_CFF.read_text())
    authors = meta.get("authors", [])

    def full(person: dict) -> str:
        return " ".join(filter(None, [person.get("given-names"), person.get("family-names")]))

    def initials(person: dict) -> str:
        given = (person.get("given-names") or "").split()
        return f"{person.get('family-names', '')} {''.join(g[0] for g in given)}".strip()

    year = str(meta["date-released"])[:4]
    plain = (
        f"{', '.join(initials(a) for a in authors)} ({year}). "
        f"{meta['title']}. Version {meta['version']}. {meta['repository-code']}"
    )
    key = f"{(authors[0].get('family-names') or 'software').lower()}{year}pyplatypus"
    bibtex = "\n".join(
        [
            f"@software{{{key},",
            f"  author  = {{{' and '.join(full(a) for a in authors)}}},",
            f"  title   = {{{meta['title']}}},",
            f"  year    = {{{year}}},",
            f"  version = {{{meta['version']}}},",
            f"  url     = {{{meta['repository-code']}}}",
            "}",
        ]
    )

    CITATION_PAGE.write_text(
        "\n".join(
            [
                "---",
                'title: "Citation"',
                "---",
                "",
                "<!-- GENERATED by tools/build_reference.py from CITATION.cff. Do not edit. -->",
                "",
                meta.get("message", "If you use this software, please cite it."),
                "",
                f"> {plain}",
                "",
                "```bibtex",
                bibtex,
                "```",
                "",
                (
                    "The machine-readable form is "
                    f"[`CITATION.cff`]({meta['repository-code']}/blob/main/CITATION.cff), "
                    'which is what GitHub\'s "Cite this repository" reads.'
                ),
                "",
                "The R package is cited separately, because it is a separate piece of software:",
                '`citation("platypus")` in R, or the',
                "[Citation page](https://maju116.github.io/platypus/CITATION.html) on its site.",
                "",
            ]
        )
    )
    print(f"About: Citation <- CITATION.cff (version {meta['version']})")


def about_files() -> list[str]:
    return [target for _, kind, target in ABOUT if kind == "page" and (ROOT / target).exists()]


def sidebar_about() -> list[dict]:
    entries = []
    for text, kind, target in ABOUT:
        if kind == "link":
            entries.append({"text": text, "href": target})
            continue
        if not (ROOT / target).exists():
            print(f"About: skipping {text} - no {target}")
            continue
        entries.append({"text": text, "file": target})
    return entries


def sidebar_reference(groups: list[dict]) -> list[dict]:
    return [
        {
            "section": group["title"],
            "contents": [f"reference/{entry}.qmd" for entry in group["contents"]],
        }
        for group in groups
    ]


def main() -> None:
    build_citation_page()
    groups = yaml.safe_load(GROUPS.read_text())["groups"]

    config = {
        "project": {
            "type": "website",
            "output-dir": "docs",
            # An explicit list: a Quarto project at the repository root would otherwise
            # render README.md and CHANGELOG.md as pages of the site.
            # Named individually rather than by a glob: a glob would also pull in
            # README.md, which is GitHub's front page and opens with badges that mean
            # nothing on a site carrying its own navigation.
            "render": ["index.qmd", "guide.qmd", "config.qmd", "reference/", *about_files()],
            # The JSON Schema is not a page, so Quarto would not copy it to the site. It has
            # to be there, because its own `$id` is that address and an editor fetches it to
            # validate a configuration as it is typed - and until 0.7.0a3 that address was a
            # 404, which is a promise nothing kept.
            "resources": ["schema/"],
        },
        "brand": "_brand.yml",
        "website": {
            "title": "pyplatypus",
            "favicon": "assets/hexsticker.png",
            "navbar": {
                "search": True,
                "right": [
                    {
                        "icon": "github",
                        "href": "https://github.com/maju116/pyplatypus",
                        "aria-label": "pyplatypus on GitHub",
                    }
                ],
            },
            "sidebar": {
                "style": "docked",
                "collapse-level": 2,
                "contents": [
                    {"text": "Home", "file": "index.qmd"},
                    {
                        "section": "Reference",
                        "contents": [
                            # quartodoc's listing carries each group's description, which
                            # the sidebar does not show, so it is worth keeping - but it
                            # inherits the section's title and would read "Reference"
                            # twice.
                            {"text": "Overview", "file": "reference/index.qmd"},
                            *sidebar_reference(groups),
                        ],
                    },
                    # One entry today and a section rather than a bare link, because the
                    # guides are what this site is missing beside the R package's three
                    # vignettes, and a reader looking for them should find a place for them
                    # rather than a page filed under Reference.
                    # The walk first, the exhaustive reference second: one is read and the
                    # other is looked things up in.
                    {
                        "section": "Guides",
                        "contents": [
                            {"text": "Writing a configuration", "file": "guide.qmd"},
                            {"text": "Every configuration field", "file": "config.qmd"},
                        ],
                    },
                    {"section": "About", "contents": sidebar_about()},
                ],
            },
        },
        "format": {"html": {"toc": True}},
        "quartodoc": {
            "package": "pyplatypus",
            "dir": "reference",
            "title": "Reference",
            "style": "pkgdown",
            "render_interlinks": False,
            # Our docstrings are Google-style - `Args:`, `Returns:`, `Raises:` - and saying
            # so matters twice. It is what they are, and quartodoc otherwise reaches for the
            # NumPy parser, which in the installed griffe raises
            # `parse_numpy() got an unexpected keyword argument` and takes the build with it.
            "parser": "google",
            "sections": groups,
        },
    }

    CONFIG.write_text(HEADER + yaml.safe_dump(config, sort_keys=False, width=92))
    print(f"_quarto.yml: {len(groups)} groups, {sum(len(g['contents']) for g in groups)} entries")


if __name__ == "__main__":
    main()
