#!/usr/bin/env python
"""Write `_quarto.yml` from `tools/reference-groups.yml`.

The grouping is a judgement and lives in that file; this turns it into the two things that
have to agree about it - quartodoc's `sections`, which decide what gets a page, and the
website sidebar, which decides what can be clicked. Generated rather than typed twice,
because 48 entries in two places is 48 chances to disagree.

The sidebar is the reason this exists at all. `auto: reference/*` lists every generated
page in one flat section - measured: 50 items, one section - while the R package's sidebar
has eight nested groups. A flat list of fifty is not navigation.

Run it after adding or renaming a public symbol. `tests/test_reference_groups.py` fails
when the two have drifted.
"""

from __future__ import annotations

import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
GROUPS = ROOT / "tools" / "reference-groups.yml"
CONFIG = ROOT / "_quarto.yml"

HEADER = """# GENERATED by tools/build_reference.py from tools/reference-groups.yml. Do not edit the
# `quartodoc.sections` or the sidebar's Reference section here; edit the grouping there.
#
# The engine's documentation, deliberately the same shape as the R package's site - same
# Quarto, same `_brand.yml`, the same eight groups - because a reader moving between them
# should not have to learn a second site. Verified rather than asserted: both sites produce
# a byte-identical bootstrap stylesheet, which Quarto names by the hash of its content.
#
# The reference is generated by quartodoc from the docstrings, so it cannot drift from the
# code, and the `>>>` examples in it are run by pytest - which means the site cannot show
# an example that does not work.
"""


def sidebar_reference(groups: list[dict]) -> list[dict]:
    return [
        {
            "section": group["title"],
            "contents": [f"reference/{entry}.qmd" for entry in group["contents"]],
        }
        for group in groups
    ]


def main() -> None:
    groups = yaml.safe_load(GROUPS.read_text())["groups"]

    config = {
        "project": {
            "type": "website",
            "output-dir": "docs",
            # An explicit list: a Quarto project at the repository root would otherwise
            # render README.md and CHANGELOG.md as pages of the site.
            "render": ["index.qmd", "reference/"],
        },
        "brand": "_brand.yml",
        "website": {
            "title": "pyplatypus",
            "favicon": "assets/hexsticker.png",
            "navbar": {
                "search": True,
                "right": [
                    {
                        "icon": "github",
                        "href": "https://github.com/maju116/pyplatypus",
                        "aria-label": "pyplatypus on GitHub",
                    }
                ],
            },
            "sidebar": {
                "style": "docked",
                "collapse-level": 2,
                "contents": [
                    {"text": "Home", "file": "index.qmd"},
                    {
                        "section": "Reference",
                        "contents": [
                            # quartodoc's listing carries each group's description, which
                            # the sidebar does not show, so it is worth keeping - but it
                            # inherits the section's title and would read "Reference"
                            # twice.
                            {"text": "Overview", "file": "reference/index.qmd"},
                            *sidebar_reference(groups),
                        ],
                    },
                ],
            },
        },
        "format": {"html": {"toc": True}},
        "quartodoc": {
            "package": "pyplatypus",
            "dir": "reference",
            "title": "Reference",
            "style": "pkgdown",
            "render_interlinks": False,
            # Our docstrings are Google-style - `Args:`, `Returns:`, `Raises:` - and saying
            # so matters twice. It is what they are, and quartodoc otherwise reaches for the
            # NumPy parser, which in the installed griffe raises
            # `parse_numpy() got an unexpected keyword argument` and takes the build with it.
            "parser": "google",
            "sections": groups,
        },
    }

    CONFIG.write_text(HEADER + yaml.safe_dump(config, sort_keys=False, width=92))
    print(
        f"_quarto.yml: {len(groups)} groups, "
        f"{sum(len(g['contents']) for g in groups)} entries"
    )


if __name__ == "__main__":
    main()
